// tslint:disable
/**
 * LocalAPI Portal API
 * The backend service used by the localAPI Portal UI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, throwIfRequired, encodeURI } from '../runtime';
import { Response } from '../models';

export interface GetVoucherStateUsingGETRequest {
  code: string;
}

/**
 * no description
 */
export class VoucherControllerApi extends BaseAPI {
  /**
   * getVoucherState
   */
  getVoucherStateUsingGET = (requestParameters: GetVoucherStateUsingGETRequest): Observable<Response> => {
    throwIfRequired(requestParameters, 'code', 'getVoucherStateUsingGET');

    return this.request<Response>({
      path: '/voucher/{code}'.replace('{code}', encodeURI(requestParameters.code)),
      method: 'GET'
    });
  };
}
