// tslint:disable
/**
 * LocalAPI Portal API
 * The backend service used by the localAPI Portal UI
 *
 * The version of the OpenAPI document: 0.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface LicenseFileRequest
 */
export interface LicenseFileRequest {
  /**
   * @type {string}
   * @memberof LicenseFileRequest
   */
  email?: string;
  /**
   * @type {string}
   * @memberof LicenseFileRequest
   */
  serialNumber?: string;
  /**
   * @type {string}
   * @memberof LicenseFileRequest
   */
  voucherCode?: string;
}
